apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-er-sync
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9012
  liveness:
    path: /isAlive
    initialDelay: 40
  readiness:
    path: /isReady
    initialDelay: 40
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  openSearch:
    access: admin
    instance: stilling
  accessPolicy:
    outbound:
      external:
        - host: data.brreg.no
          ports:
            - port: 443
