apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-er-sync-odfe
  namespace: default
  labels:
    team: teampam
spec:
  image: repo.adeo.no:5443/pam-er-sync-odfe:1.17_odfe_1
  port: 9012
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  liveness:
    initialDelay: 40
    path: /isAlive
  readiness:
    initialDelay: 40
    path: /isReady
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi
  webproxy: true
  vault:
    enabled: false
  ingresses:
    - https://pam-er-sync-odfe.nais.oera.no
  env:
    - name: STILLINGESBACKEND_URL
      value: https://tpa-stilling-opendistro-elasticsearch.nais.oera.no
