server:
  port: 9012
application:
  version: @project.version@
pam:
  elasticsearch:
    url: ${STILLINGESBACKEND_URL:https://pamsok-elasticsearch.nais.oera-q.local}
spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    platform: h2
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
       cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class:  org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  profiles:
    active: prod
  batch:
    job:
      enabled: false
    initialize-schema: always

# HTTP proxy, see HttpConfig class.
http:
  proxy:
    enabled: true
    url: http://155.55.60.117:8088

# Management endpoints for NAIS.
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus
  endpoint:
      prometheus:
        enabled: true
      health:
        enabled: true
      info:
        enabled: true
  metrics:
    enable:
      jvm:
        classes:
          loaded: false
          unloaded: false
        threads:
          daemon: false
          peak: false
      process:
        start:
          time: false
    export:
      prometheus:
        enabled: true