server:
  port: 9012
spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    platform: h2
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
       cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class:  org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  profiles:
    active: test
  batch:
    job:
      enabled: false # disabled batch startup, we are using scheduler
    initialize-schema: always

pam:
  http:
      proxy:
        url: http://webproxy-nais.nav.no:8088
  elasticsearch:
    url: localhost:9012
  enhetsregister:
    scheduler:
      enabled: false
      cron: 0 0 0 * * *
    sources:
      timeout:
        millis: 25000
      hovedenhet:
        enabled: false
        url:  http://data.brreg.no/enhetsregisteret/download/enheter
      underenhet:
        enabled: true
        url: http://data.brreg.no/enhetsregisteret/download/underenheter

# Management endpoints for NAIS.
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus
  endpoint:
      prometheus:
        enabled: true
      health:
        enabled: true
      info:
        enabled: true
  metrics:
    enable:
      jvm:
        classes:
          loaded: false
          unloaded: false
        threads:
          daemon: false
          peak: false
      process:
        start:
          time: false
    export:
      prometheus:
        enabled: true