server:
  port: ${server.port:9012}
application:
  version: @project.version@
spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    platform: h2
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
       cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class:  org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  profiles:
    active: prod
  batch:
    job:
      enabled: false
    initialize-schema: always

pam:
  http:
      proxy:
        url: ${PAM_NAIS_DRIFTPROXY_URL:http://webproxy-nais.nav.no:8088}
  elasticsearch:
    url: ${STILLINGESBACKEND_URL:https://pamsok-elasticsearch.nais.oera-q.local}
  enhetsregister:
    scheduler:
      enabled: ${pam.enhetsregister.scheduler.enabled:false}
      cron: ${pam.enhetsregister.scheduler.cron:0 0 0 * * *}
    sources:
      timeout:
        millis: ${pam.enhetsregister.sources.timeout.millis:25000}
      hovedenhet:
        enabled: ${pam.enhetsregister.sources.hovedenhet.enabled:false}
        url:  ${pam.enhetsregister.sources.hovedenhet.url:http://data.brreg.no/enhetsregisteret/download/enheter}
      underenhet:
        enabled: ${pam.enhetsregister.sources.underenhet.enabled:true}
        url: ${pam.enhetsregister.sources.underenhet.url:http://data.brreg.no/enhetsregisteret/download/underenheter}

# Management endpoints for NAIS.
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus
  endpoint:
      prometheus:
        enabled: true
      health:
        enabled: true
      info:
        enabled: true
  metrics:
    enable:
      jvm:
        classes:
          loaded: false
          unloaded: false
        threads:
          daemon: false
          peak: false
      process:
        start:
          time: false
    export:
      prometheus:
        enabled: true