apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: teampam
  name: pam-er-sync-dev-underenheter
  namespace: teampam
spec:
  image: {{ image }}
  schedule: "30 2 * * *" # GMT
  activeDeadlineSeconds: 60

  env:
    - name: ES_STILLING_BACKEND
      value: https://opensearch-teampam-stilling-nav-dev.aivencloud.com:26482
  envFrom:
    - secret: pam-er-sync-dev-underenheter-env

  accessPolicy:
    outbound:
      external:
        - host: opensearch-teampam-stilling-nav-dev.aivencloud.com
