apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: teampam
  name: pam-er-sync-dev-underenheter
  namespace: teampam
spec:
  image: {{ image }}
  schedule: "0 5 * * *" # GMT
  activeDeadlineSeconds: 60

  env:
    - name: ES_STILLING_BACKEND
      value: https://opensearch-teampam-stilling-nav-dev.aivencloud.com:26482
    - name: ES_USER
      value: {{ OPEN_SEARCH_USERNAME}}
    - name: ES_PASSWORD
      value: {{ OPEN_SEARCH_PASSWORD }}

  accessPolicy:
    outbound:
      external:
        - host: opensearch-teampam-stilling-nav-dev.aivencloud.com

  openSearch:
    access: write
    instance: stilling

