name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - master
jobs:
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v2
    with:
      JAVA_VERSION: 12
      BUILD_CACHE: maven
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

