name: deploy-dev-underenheter
on:
  push:
    paths:
      - dev-underenheter/**
      - .github/workflows/deploy-dev-underenheter.yml
    branches:
      - master
      - feature/**
jobs:
  build-and-deploy:
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v7
    permissions:
      actions: read
      contents: write
      security-events: write
      id-token: write
    with:
      CODEQL_ENABLED: false
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
      WORKING_DIRECTORY: "./dev-underenheter/"
      IMAGE_SUFFIX: "dev-underenheter"
      NAIS_RESOURCE: "./dev-underenheter/naisjob.yml"
      LANGUAGE: "bash"
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
