name: deploy-dev-underenheter
on:
  push:
    paths:
      - dev-underenheter/**
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build and push image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dev-underenheter
          VTAG=$(TZ=Europe/Oslo date +"%y.%j.%H%M%S")
          IMAGE=docker.pkg.github.com/$GITHUB_REPOSITORY/dev-underenheter:$VTAG
          docker build . --pull -t "$IMAGE"
          echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com --username "$GITHUB_REPOSITORY" --password-stdin
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"
          echo $IMAGE
      - name: deploy naisjob to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: dev-underenheter/naisjob.yml
