name: deploy-dev-underenheter
on:
  push:
    paths:
      - dev-underenheter/**
      - .github/workflows/deploy-dev-underenheter.yml
    branches:
      - master
      - feature/**
jobs:
  change-directory:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: change to the dev-underenheter directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd dev-underenheter
  build-and-deploy:
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v7
    permissions:
      actions: read
      contents: write
      security-events: write
      id-token: write
    with:
      CODEQL_ENABLED: false
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
      NAIS_RESOURCE: "naisjob.yml"
      IMAGE_SUFFIX: "-dev-underenheter"
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
