name: deploy-prod
on:
  release:
    types: [published]

jobs:
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-prod.yml@v2
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
